interface=wlan_onboard
driver=nl80211

ssid={{SSID_2G}}
country_code={{COUNTRY_CODE}}
ieee80211d=1

hw_mode=g
channel=6
ieee80211n=1

ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40]

wpa=2
wpa_passphrase={{WPA_PASSPHRASE}}
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
